services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_apis
    working_dir: /var/www
    volumes:
      - /Applications/XAMPP/xamppfiles/htdocs/news_apis:/var/www
    environment:
      - MAIL_MAILER=smtp
      - MAIL_HOST=live.smtp.mailtrap.io
      - MAIL_PORT=587
      - MAIL_USERNAME=api
      - MAIL_PASSWORD=f651a3e4a42c49e2bdd990e25fc3aa22
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=hello@demomailtrap.com
      - MAIL_FROM_NAME="${APP_NAME}"
    networks:
      - laravel

  # MySQL service
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: news_apis
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - /Applications/XAMPP/xamppfiles/htdocs/news_apis:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
