services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_apis
    working_dir: /var/www
    volumes:
      - ${PROJECT_PATH}:/var/www
    networks:
      - laravel

  # MySQL service
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: news_apis
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
